%% Combine Data Across Days........................................................
% 
%	Goal: Combine Data Variables Across Days for Plotting/Analysis 
% 
% 	Created:		6-3-17	ahamilos
% 	Last Modified:	6-3-17 	ahamilos
% 
% 	Instructions:
% 		Use the following functions to generate variables for a given day:
% 			1. extract_trials_gfit_v1.m --> Gets values_by_trial with global smooth-fit dF/F

% 			1.5. axclusion = ExcluderInterface(d18_DLS_values_by_trial, d18_SNc_values_by_trial, d18_lick_times_by_trial)
%			1.51. check exclusions with 
% 				heatmap_3_fx(axclusion.Excluder.SNc_data, axclusion.Excluder.lick_times_by_trial_excluded, 1)
% 				Save the following:
					d18_gfit_SNc 			= gfit_SNc;
					d18_gfit_DLS 			= gfit_DLS;
					d18_SNc_ex1_values_by_trial	= axclusion.Excluder.SNc_data;
					d18_SNc_values_by_trial	= SNc_values_by_trial;
					d18_SNc_times_by_trial 	= SNc_times_by_trial;
					d18_DLS_ex1_values_by_trial 	= axclusion.Excluder.DLS_data;
					d18_DLS_values_by_trial 	= DLS_values_by_trial;
					d18_DLS_times_by_trial 	= DLS_times_by_trial;
% 			2. lick_times_by_trial_fx.m 										[lick_times_by_trial] = lick_times_by_trial_fx(lick_times, cue_on_times, 17, num_trials)
%				Save the following:
					d18_lick_times_by_trial 	= lick_times_by_trial;
					d18_lick_ex1_times_by_trial = axclusion.Excluder.lick_times_by_trial_excluded;
% 			3. first_lick_grabber_operant.m 									[f_lick_rxn, f_lick_train_abort, f_lick_operant_no_rew, f_lick_operant_rew, f_lick_ITI, trials_with_rxn, trials_with_train, trials_with_ITI, all_first_licks] = first_lick_grabber_operant_fx(lick_times_by_trial, num_trials)
% 				Save the following:
					d18_f_lick_rxn 			= f_lick_rxn;
					d18_f_lick_train_abort  	= f_lick_train_abort;
					d18_f_lick_operant_no_rew = f_lick_operant_no_rew;
					d18_f_lick_operant_rew 	= f_lick_operant_rew;
					% d18_f_lick_pavlovian     = f_lick_pavlovian;
					d18_f_lick_ITI			= f_lick_ITI;
					d18_all_first_licks 		= all_first_licks;
%			4. Run the appropriate first_lick_grabber with the excluded data 
%			and save this next (its the output of the fx, so dont need to type these in usually)
					d18_f_ex1_lick_rxn 			= f_lick_rxn;
					d18_f_ex1_lick_train_abort  	= f_lick_train_abort;
					d18_f_ex1_lick_operant_no_rew = f_lick_operant_no_rew;
					d18_f_ex1_lick_operant_rew 	= f_lick_operant_rew;
% 					d18_f_ex1_lick_pavlovian     = f_lick_pavlovian;
					d18_f_ex1_lick_ITI			= f_lick_ITI;
					d18_all_ex1_first_licks 		= all_first_licks;


% 			5. Run the LTA file to also get the LTA arrays and save:
% 					1. lick_triggered_ave_allplots_fx.m
 					d22_rxn_DLS_lick_triggered_ave_ignore_NaN = rxn_DLS_lick_triggered_ave_ignore_NaN;
					d22_rxn_SNc_lick_triggered_ave_ignore_NaN = rxn_SNc_lick_triggered_ave_ignore_NaN;
					d22_early_DLS_lick_triggered_ave_ignore_NaN = early_DLS_lick_triggered_ave_ignore_NaN;
					d22_early_SNc_lick_triggered_ave_ignore_NaN = early_SNc_lick_triggered_ave_ignore_NaN;
					d22_rew_DLS_lick_triggered_ave_ignore_NaN = 	rew_DLS_lick_triggered_ave_ignore_NaN;
					d22_rew_SNc_lick_triggered_ave_ignore_NaN = 	rew_SNc_lick_triggered_ave_ignore_NaN;
					% d22_pav_DLS_lick_triggered_ave_ignore_NaN = 	pav_DLS_lick_triggered_ave_ignore_NaN;
					% d22_pav_SNc_lick_triggered_ave_ignore_NaN = 	pav_SNc_lick_triggered_ave_ignore_NaN;
					d22_N_rxn_DLS = 	N_rxn_DLS;
					d22_N_rxn_SNc = 	N_rxn_SNc;
					d22_N_early_DLS = 	N_early_DLS;
					d22_N_early_SNc = 	N_early_SNc;
					d22_N_rew_DLS = 	N_rew_DLS;
					d22_N_rew_SNc = 	N_rew_SNc;
					% d22_N_pav_DLS = 	N_pav_DLS;
					% d22_N_pav_SNc = 	N_pav_SNc;
					d22_N_ITI_DLS =     N_ITI_DLS
					d22_N_ITI_SNc      =N_ITI_SNc
					d22_time_array = time_array;
					% d22_pav_DLS_lick_triggered_trials = pav_DLS_lick_triggered_trials;
					% d22_pav_SNc_lick_triggered_trials = pav_SNc_lick_triggered_trials;
					d22_rxn_DLS_lick_triggered_trials = rxn_DLS_lick_triggered_trials;
					d22_early_DLS_lick_triggered_trials = early_DLS_lick_triggered_trials;
					d22_rew_DLS_lick_triggered_trials = rew_DLS_lick_triggered_trials;
					d22_rxn_SNc_lick_triggered_trials = rxn_SNc_lick_triggered_trials;
					d22_early_SNc_lick_triggered_trials = early_SNc_lick_triggered_trials;
					d22_rew_SNc_lick_triggered_trials = rew_SNc_lick_triggered_trials;


% 				
% 
% 
% 		Create a Header in the Folder (include date run and versions of files)
% 		
% 		Open variables from each day you want to consider into workspace
% 
% 		Paste in names into the categories below and run!
% 
% 		Then use time_binner_fx with the combined data
% print('-depsc','-painters','-loose','Figure 4')
%-------------------------------------------------------------------------------------

% DLS--------------------------------------------------------------------------------- 
combined_DLS_values_by_trial	= vertcat(d18_DLS_values_by_trial,...
										d18_DLS_values_by_trial,...
										DLS_values_by_trial);

combined_DLS_times_by_trial 	= vertcat(d18_DLS_times_by_trial,...
										d18_DLS_times_by_trial,...
										DLS_times_by_trial);

% SNc--------------------------------------------------------------------------------- 
combined_SNc_values_by_trial	= vertcat(d18_SNc_values_by_trial,...
										d18_SNc_values_by_trial,...
										SNc_values_by_trial);

combined_SNc_times_by_trial 	= vertcat(d18_SNc_times_by_trial,...
										d18_SNc_times_by_trial,...
										SNc_times_by_trial);

% Both-------------------------------------------------------------------------------- 
% combined_lick_times_by_trial 	= [ 	,...
% 										,...
% 										];									

% combined_f_lick_rxn			 	= [ 	,...
% 										,...
% 										];

% % combined_f_lick_train_abort  	= [ 	,...
% % 										,...
% 										% ];

% combined_f_lick_operant_no_rew 	= horzcat(d18_f_lick_operant_no_rew,...
% 										d18_f_lick_operant_no_rew,...
% 										f_lick_operant_no_rew);	

% combined_f_lick_operant_rew 	= horzcat(d18_f_lick_operant_rew,...
% 										d18_f_lick_operant_rew,...
% 										f_lick_operant_rew);			

% % combined_f_lick_pavlovian	 	= [ 	,...
% % 										,...
% % 										];									

% % combined_f_lick_ITI			 	= [ 	,...
% % 										,...
% % 										];

% combined_all_first_licks	 	= horzcat(d##_all_first_licks,...
% 										d##_all_first_licks,...
% 										d##_all_first_licks);										

										 


combined_DLS_ex_values_by_trial = vertcat(d##_DLS_ex_values_by_trial,...
										d##_DLS_ex_values_by_trial,...
										d##_DLS_ex_values_by_trial);


combined_SNc_ex_values_by_trial = vertcat(d##_SNc_ex_values_by_trial,...
										d##_SNc_ex_values_by_trial,...
										d##_SNc_ex_values_by_trial);


combined_all_ex_first_licks = horzcat(d##_all_ex_first_licks,...
										d##_all_ex_first_licks,...
										d##_all_ex_first_licks);


combined_f_ex_lick_rxn  = horzcat(d##_f_ex_lick_rxn,...
										d##_f_ex_lick_rxn,...
										d##_f_ex_lick_rxn);


combined_f_ex_lick_operant_no_rew = horzcat(d##_f_ex_lick_operant_no_rew,...
										d##_f_ex_lick_operant_no_rew,...
										d##_f_ex_lick_operant_no_rew);


combined_f_ex_lick_operant_rew = horzcat(d##_f_ex_lick_operant_rew,...
										d##_f_ex_lick_operant_rew,...
										d##_f_ex_lick_operant_rew);


combined_f_ex_lick_ITI = horzcat(d##_f_ex_lick_ITI,...
										d##_f_ex_lick_ITI,...
										d##_f_ex_lick_ITI);


%LTA
combined_time_array = d##_time_array%only one of the time arrays will suffice


combined_early_DLS_lick_triggered_trials = vertcat(d##_early_DLS_lick_triggered_trials,...
										d##_early_DLS_lick_triggered_trials,...
										d##_early_DLS_lick_triggered_trials);


combined_rew_DLS_lick_triggered_trials = vertcat(d##_rew_DLS_lick_triggered_trials,...
										d##_rew_DLS_lick_triggered_trials,...
										d##_rew_DLS_lick_triggered_trials);


combined_early_SNc_lick_triggered_trials = vertcat(d##_early_SNc_lick_triggered_trials,...
										d##_early_SNc_lick_triggered_trials,...
										d##_early_SNc_lick_triggered_trials);


combined_rew_SNc_lick_triggered_trials = vertcat(d##_rew_SNc_lick_triggered_trials,...
										d##_rew_SNc_lick_triggered_trials,...
										d##_rew_SNc_lick_triggered_trials);

















%%% SCRATCH WORK:


combined_DLS_values_by_trial	= vertcat(d17_DLS_values_by_trial,...
										d18_DLS_values_by_trial(:,1:18501),...
										d19_DLS_values_by_trial,...
										d20_DLS_values_by_trial,...
										d21_DLS_values_by_trial,...
										d22_DLS_values_by_trial,...
										d23_DLS_values_by_trial,...
										d24_DLS_values_by_trial,...
										d25_DLS_values_by_trial,...
										d26_DLS_values_by_trial);


combined_SNc_values_by_trial	= vertcat(d17_SNc_values_by_trial,...
										d18_SNc_values_by_trial(:,1:18501),...
										d19_SNc_values_by_trial,...
										d20_SNc_values_by_trial,...
										d21_SNc_values_by_trial,...
										d22_SNc_values_by_trial,...
										d23_SNc_values_by_trial,...
										d24_SNc_values_by_trial,...
										d25_SNc_values_by_trial,...
										d26_SNc_values_by_trial);	 


combined_DLS_ex_values_by_trial = vertcat(d17_DLS_ex1_values_by_trial,...
										d18_DLS_ex1_values_by_trial(:,1:18501),...
										d19_DLS_ex1_values_by_trial,...
										d20_DLS_ex1_values_by_trial,...
										d21_DLS_ex1_values_by_trial,...
										d22_DLS_ex1_values_by_trial,...
										d23_DLS_ex1_values_by_trial,...
										d24_DLS_ex1_values_by_trial,...
										d25_DLS_ex1_values_by_trial,...
										d26_DLS_ex1_values_by_trial);


combined_SNc_ex_values_by_trial = vertcat(d17_SNc_ex1_values_by_trial,...
										d18_SNc_ex1_values_by_trial(:,1:18501),...
										d19_SNc_ex1_values_by_trial,...
										d20_SNc_ex1_values_by_trial,...
										d21_SNc_ex1_values_by_trial,...
										d22_SNc_ex1_values_by_trial,...
										d23_SNc_ex1_values_by_trial,...
										d24_SNc_ex1_values_by_trial,...
										d25_SNc_ex1_values_by_trial,...
										d26_SNc_ex1_values_by_trial);


combined_all_ex_first_licks = horzcat(d17_all_ex1_first_licks,...
										d18_all_ex1_first_licks,...
										d19_all_ex1_first_licks,...
										d20_all_ex1_first_licks,...
										d21_all_ex1_first_licks,...
										d22_all_ex1_first_licks,...
										d23_all_ex1_first_licks,...
										d24_all_ex1_first_licks,...
										d25_all_ex1_first_licks,...
										d26_all_ex1_first_licks);


combined_f_ex_lick_rxn  = horzcat(d17_f_ex1_lick_rxn,...
										d18_f_ex1_lick_rxn,...
										d19_f_ex1_lick_rxn,...
										d20_f_ex1_lick_rxn,...
										d21_f_ex1_lick_rxn,...
										d22_f_ex1_lick_rxn,...
										d23_f_ex1_lick_rxn,...
										d24_f_ex1_lick_rxn,...
										d25_f_ex1_lick_rxn,...
										d26_f_ex1_lick_rxn);



combined_f_ex_lick_operant_no_rew = horzcat(d17_f_ex1_lick_operant_no_rew,...
										d18_f_ex1_lick_operant_no_rew,...
										d19_f_ex1_lick_operant_no_rew,...
										d20_f_ex1_lick_operant_no_rew,...
										d21_f_ex1_lick_operant_no_rew,...
										d22_f_ex1_lick_operant_no_rew,...
										d23_f_ex1_lick_operant_no_rew,...
										d24_f_ex1_lick_operant_no_rew,...
										d25_f_ex1_lick_operant_no_rew,...
										d26_f_ex1_lick_operant_no_rew);


combined_f_ex_lick_operant_rew = horzcat(d17_f_ex1_lick_operant_rew,...
										d18_f_ex1_lick_operant_rew,...
										d19_f_ex1_lick_operant_rew,...
										d20_f_ex1_lick_operant_rew,...
										d21_f_ex1_lick_operant_rew,...
										d22_f_ex1_lick_operant_rew,...
										d23_f_ex1_lick_operant_rew,...
										d24_f_ex1_lick_operant_rew,...
										d25_f_ex1_lick_operant_rew,...
										d26_f_ex1_lick_operant_rew);


combined_f_ex_lick_ITI = horzcat(d17_f_ex1_lick_ITI,...
										d18_f_ex1_lick_ITI,...
										d19_f_ex1_lick_ITI,...
										d20_f_ex1_lick_ITI,...
										d21_f_ex1_lick_ITI,...
										d22_f_ex1_lick_ITI,...
										d23_f_ex1_lick_ITI,...
										d24_f_ex1_lick_ITI,...
										d25_f_ex1_lick_ITI,...
										d26_f_ex1_lick_ITI);


%LTA
combined_time_array = d17_time_array;%only one of the time arrays will suffice


combined_early_DLS_lick_triggered_trials = vertcat(d17_early_DLS_lick_triggered_trials,...
										d18_early_DLS_lick_triggered_trials,...
										d19_early_DLS_lick_triggered_trials,...
										d20_early_DLS_lick_triggered_trials,...
										d21_early_DLS_lick_triggered_trials,...
										d22_early_DLS_lick_triggered_trials,...
										d23_early_DLS_lick_triggered_trials,...
										d24_early_DLS_lick_triggered_trials,...
										d25_early_DLS_lick_triggered_trials,...
										d26_early_DLS_lick_triggered_trials);


combined_rew_DLS_lick_triggered_trials = vertcat(d17_rew_DLS_lick_triggered_trials,...
										d18_rew_DLS_lick_triggered_trials,...
										d19_rew_DLS_lick_triggered_trials,...
										d20_rew_DLS_lick_triggered_trials,...
										d21_rew_DLS_lick_triggered_trials,...
										d22_rew_DLS_lick_triggered_trials,...
										d23_rew_DLS_lick_triggered_trials,...
										d24_rew_DLS_lick_triggered_trials,...
										d25_rew_DLS_lick_triggered_trials,...
										d26_rew_DLS_lick_triggered_trials);


combined_early_SNc_lick_triggered_trials = vertcat(d17_early_SNc_lick_triggered_trials,...
										d18_early_SNc_lick_triggered_trials,...
										d19_early_SNc_lick_triggered_trials,...
										d20_early_SNc_lick_triggered_trials,...
										d21_early_SNc_lick_triggered_trials,...
										d22_early_SNc_lick_triggered_trials,...
										d23_early_SNc_lick_triggered_trials,...
										d24_early_SNc_lick_triggered_trials,...
										d25_early_SNc_lick_triggered_trials,...
										d26_early_SNc_lick_triggered_trials);


combined_rew_SNc_lick_triggered_trials = vertcat(d17_rew_SNc_lick_triggered_trials,...
										d18_rew_SNc_lick_triggered_trials,...
										d19_rew_SNc_lick_triggered_trials,...
										d20_rew_SNc_lick_triggered_trials,...
										d21_rew_SNc_lick_triggered_trials,...
										d22_rew_SNc_lick_triggered_trials,...
										d23_rew_SNc_lick_triggered_trials,...
										d24_rew_SNc_lick_triggered_trials,...
										d25_rew_SNc_lick_triggered_trials,...
										d26_rew_SNc_lick_triggered_trials);



