function [trial_start_times,...
 cue_on_times,...
 juice_times,... 
 lampOn_times,... 
 lick_times,...
 trigger_times,...
 keyboard_times,...
 keyboard_codes,...
 num_trials_plus_1,...
 num_trials] = extract_digital_variables_fx(filename);





end