function y = cedBandpass1(x)
%cedBandpass1 Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the DSP System Toolbox 9.2.
% Generated on: 10-Apr-2017 19:41:56

persistent Hd;

if isempty(Hd)
    
    Fstop1 = 0.1;   % First Stopband Frequency
    Fpass1 = 1;     % First Passband Frequency
    Fpass2 = 20;    % Second Passband Frequency
    Fstop2 = 21;    % Second Stopband Frequency
    Astop1 = 60;    % First Stopband Attenuation (dB)
    Apass  = 1;     % Passband Ripple (dB)
    Astop2 = 60;    % Second Stopband Attenuation (dB)
    Fs     = 1000;  % Sampling Frequency
    
    h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
        Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
    
    Hd = design(h, 'butter', ...
        'MatchExactly', 'stopband', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

