%% MouseBehaviorInterface: construct graphical user interface to interact with arduino
classdef MouseBehaviorInterface < handle
	properties
		Arduino
		Figure
		Rsc
	end

	methods
		function obj = MouseBehaviorInterface()
			% Establish arduino connection
			obj.Arduino = ArduinoConnection;

			% Create the frame
			obj.Rsc.Figure = figure('Position',[100 100 400 200]);

			% Create a uitable for parameters
			obj.Rsc.TableParams = uitable...
			(...
				'Data', obj.Arduino.ParamValues',...
				'RowName', obj.Arduino.ParamNames,... 
				'ColumnName', {'Value'},...
				'ColumnFormat', {'long'},...
				'ColumnEditable', [true],...
				'CellEditCallback', {@obj.OnParamChanged, obj.Arduino}...
			);

			% Set width and height
			obj.Rsc.TableParams.Position(3) = obj.Rsc.TableParams.Extent(3);
			obj.Rsc.TableParams.Position(4) = obj.Rsc.TableParams.Extent(4);

			% Start button - start experiment from IDLE
			ctrlPosBase = obj.Rsc.TableParams.Position;
			ctrlWidth = 50; % Width
			ctrlHeight = 20; % Height
			ctrlSpacing = 10; % Spacing between ui elements
			ctrlPos = ...
			[...
				ctrlPosBase(1) + ctrlPosBase(3) + ctrlSpacing,...
				ctrlPosBase(2) + ctrlPosBase(4) - ctrlHeight - ctrlSpacing,...
				ctrlWidth,...	
				ctrlHeight...
			];
			obj.Rsc.ButtonStart = uicontrol...
			(...
				'Style', 'pushbutton',...
				'String', 'Start',...
				'Position', ctrlPos,...
				'Callback', {@MouseBehaviorInterface.ArduinoStart, obj.Arduino}...
			);

			% Stop button - abort current trial and return to IDLE
			ctrlPosBase = obj.Rsc.ButtonStart.Position;
			ctrlWidth = 50; % Width
			ctrlHeight = 20; % Height
			ctrlSpacing = 10; % Spacing between ui elements
			ctrlPos = ...
			[...
				ctrlPosBase(1),...
				ctrlPosBase(2) - ctrlHeight - ctrlSpacing,...
				ctrlWidth,...	
				ctrlHeight...
			];
			obj.Rsc.ButtonQuit = uicontrol...
			(...
				'Style', 'pushbutton',...
				'String', 'Quit',...
				'Position', ctrlPos,...
				'Callback', {@MouseBehaviorInterface.ArduinoQuit, obj.Arduino}...
			);

			% Terminate button - terminate connection w/ arduino and close GUI
			ctrlPosBase = obj.Rsc.ButtonQuit.Position;
			ctrlWidth = 50; % Width
			ctrlHeight = 20; % Height
			ctrlSpacing = 10; % Spacing between ui elements
			ctrlPos = ...
			[...
				ctrlPosBase(1),...
				ctrlPosBase(2) - ctrlHeight - ctrlSpacing,...
				ctrlWidth,...	
				ctrlHeight...
			];
			obj.Rsc.ButtonTerminate = uicontrol...
			(...
				'Style', 'pushbutton',...
				'String', 'Terminate',...
				'Position', ctrlPos,...
				'Callback', {@MouseBehaviorInterface.ArduinoTerminate, obj.Arduino, obj.Rsc.Figure}...
			);
		end
	end

	methods (Static)
		function OnParamChanged(~, editData, arduino)
			paramId = editData.Indices(1);
			newData = editData.NewData;
			arduino.ParamValues(paramId) = newData;
			arduino.UpdateParams;
		end
		function ArduinoStart(~, ~, arduino)
			arduino.Start;
		end
		function ArduinoQuit(~, ~, arduino)
			arduino.Quit;
		end
		function ArduinoTerminate(~, ~, arduino, figureHandle)
			arduino.Terminate;
			close(figureHandle)
		end
	end
end